Repository hmcts/rd-location-ref-data-load, pull requests merged in 2020-12, with the labels that each got.

#76 refactor: updated blob key names
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  charts/rd-location-ref-data-load/Chart.yaml
  charts/rd-location-ref-data-load/values.yaml
  src/main/resources/bootstrap.yaml
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-76

#78 Add sync method call
  Jenkinsfile_CNP
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-78

#81 build: Addressed CVE-2020-17527
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-81

#80 RDCC-2102 added trimming for file values
  src/functionalTest/resources/sourceFiles/service-test.csv
  src/main/java/uk/gov/hmcts/reform/locationrefdata/camel/mapper/ServiceToCcdCaseTypeMapper.java
  src/test/java/uk/gov/hmcts/reform/locationrefdata/camel/mapper/ServiceToCcdCaseTypeMapperTest.java
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-80

#86 CVE-2020-8908: Fixing the cve.
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-86
