Repository hmcts/rd-location-ref-data-load, pull requests merged in 2020-10, with the labels that each got.

#30 TF upgrade to 0.12.16 and Azure RM upgrade to 2.20.0 - Master
  build.gradle
  infrastructure/main.tf
  infrastructure/state.tf
  infrastructure/terraform.tf
  infrastructure/variables.tf
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-30

#32 TF upgrade to 0.13.3 and Azure RM upgrade to 2.25+ - Master
  infrastructure/.terraform-version
  infrastructure/terraform.tf
  infrastructure/variables.tf
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-32

#34 fix: vault keys in bootstrap.yaml
  src/main/resources/bootstrap.yaml
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-34

#35 fix: map vault keys in terra form
  infrastructure/main.tf
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-35

#36 fix: boot strap prefix enabled
  src/main/resources/bootstrap.yaml
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-36

#40 fix: boot strap values update
  infrastructure/main.tf
  src/main/resources/bootstrap.yaml
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-40

#41 fix: key vault config updated
  charts/rd-location-ref-data-load/Chart.yaml
  charts/rd-location-ref-data-load/values.yaml
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-41

#42 fix: removed health check hmcts lib from data-ingestion lib
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-42

#44 fix: bootstrap values updated
  src/main/resources/bootstrap.yaml
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-44

#45 fix: configuration refactor
  src/functionalTest/java/uk/gov/hmcts/reform/locationrefdata/config/LrdCamelConfig.java
  src/functionalTest/resources/application-integration.yml
  src/main/resources/application-lrd-router.yaml
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-45

#51 Bumpsup : Bump ups version and owasp update(RDCC-1933)
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-51

#49 refactor: Truncate & Insert Support for LRD load(RDCC-1943)
  build.gradle
  src/functionalTest/java/uk/gov/hmcts/reform/locationrefdata/cameltest/LrdApplicationExceptionAndAuditTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/locationrefdata/cameltest/LrdApplicationTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/locationrefdata/cameltest/testsupport/LrdIntegrationBaseTest.java
  src/functionalTest/resources/application-integration.yml
  src/functionalTest/resources/db/testmigration/V1_2__add_sequences.sql
  src/functionalTest/resources/db/testmigration/V1_3__alter_LRD.sql
  src/functionalTest/resources/db/testmigration/V1_5__services.sql
  src/functionalTest/resources/sourceFiles/service-test-day2.csv
  src/functionalTest/resources/sourceFiles/service-test-invalid-service-failure.csv
  src/functionalTest/resources/sourceFiles/service-test-no-insert-only-delete.csv
  src/main/java/uk/gov/hmcts/reform/locationrefdata/camel/processor/ServiceToCcdCaseTypeProcessor.java
  src/main/resources/application-lrd-router.yaml
  src/main/resources/application.yaml
  src/main/resources/db/migration/V1_2__add_sequences.sql
  src/main/resources/db/migration/V1_3__alter_LRD.sql
  src/main/resources/db/migration/V1_5__services.sql
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-49

#53 fix: reverting postgres version
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-53

#54 Fix for failing build
  Jenkinsfile_nightly
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-54

#55 Renamed secret names
  Jenkinsfile_nightly
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-55

#59 feat:library updated to check file timestamp of blob and missing blobs(RDCC-1927)
  Jenkinsfile_CNP
  build.gradle
  charts/rd-location-ref-data-load/Chart.yaml
  charts/rd-location-ref-data-load/values.preview.template.yaml
  charts/rd-location-ref-data-load/values.yaml
  src/functionalTest/java/uk/gov/hmcts/reform/locationrefdata/cameltest/LrdApplicationExceptionAndAuditTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/locationrefdata/cameltest/LrdApplicationTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/locationrefdata/cameltest/LrdFileStatusCheckTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/locationrefdata/cameltest/testsupport/LrdBlobSupport.java
  src/functionalTest/java/uk/gov/hmcts/reform/locationrefdata/cameltest/testsupport/LrdIntegrationBaseTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/locationrefdata/config/LrdCamelConfig.java
  src/functionalTest/resources/application-integration.yml
  src/functionalTest/resources/db/testmigration/V1_8__alter_audit_exception_table.sql
  src/main/java/uk/gov/hmcts/reform/locationrefdata/LrdLoadApplication.java
  src/main/java/uk/gov/hmcts/reform/locationrefdata/camel/listener/JobResultListener.java
  src/main/resources/application-camel-routes-common.yaml
  src/main/resources/db/migration/V1_8__alter_audit_exception_table.sql
  src/test/java/uk/gov/hmcts/reform/locationrefdata/camel/listener/JobResultListenerTest.java
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-59

#61 suppressing tomcat ebbed jar
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-61

#66 feat: Updated Audit/Exceptions and stale file check with data-ingestion (RDCC-1924)
  build.gradle
  src/functionalTest/java/uk/gov/hmcts/reform/locationrefdata/cameltest/LrdApplicationTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/locationrefdata/cameltest/testsupport/LrdIntegrationBaseTest.java
  src/functionalTest/resources/db/testmigration/V1_6__excption_table.sql
  src/functionalTest/resources/db/testmigration/V1_7__audit_table.sql
  src/functionalTest/resources/db/testmigration/V1_8__alter_audit_exception_table.sql
  src/main/resources/application-camel-routes-common.yaml
  src/main/resources/application-lrd-router.yaml
  src/main/resources/db/migration/V1_6__excption_table.sql
  src/main/resources/db/migration/V1_7__audit_table.sql
  src/main/resources/db/migration/V1_8__alter_audit_exception_table.sql
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-66
