Repository hmcts/rd-location-ref-data-load, pull requests merged in 2021-07, with the labels that each got.

#162 chnage order of commands to fix security scan
  security.sh
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-162

#158 RDCC-2985: File ingestion process for court venue table
  src/functionalTest/java/uk/gov/hmcts/reform/locationrefdata/cameltest/LrdApplicationExceptionAndAuditTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/locationrefdata/cameltest/LrdApplicationTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/locationrefdata/cameltest/LrdCourtVenueTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/locationrefdata/cameltest/LrdFileStatusCheckTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/locationrefdata/cameltest/testsupport/LrdIntegrationBaseTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/locationrefdata/config/LrdCamelConfig.java
  src/functionalTest/resources/application-integration.yml
  src/functionalTest/resources/db/testmigration/V1_12__building_location_test_insert.sql
  src/functionalTest/resources/sourceFiles/court-venue-failure.csv
  src/functionalTest/resources/sourceFiles/court-venue-partial-success.csv
  src/functionalTest/resources/sourceFiles/court-venue-test.csv
  src/functionalTest/resources/testData/truncate-lrd-court-venue.sql
  src/main/java/uk/gov/hmcts/reform/locationrefdata/camel/binder/CourtVenue.java
  src/main/java/uk/gov/hmcts/reform/locationrefdata/camel/constants/LrdDataLoadConstants.java
  src/main/java/uk/gov/hmcts/reform/locationrefdata/camel/mapper/CourtVenueMapper.java
  src/main/java/uk/gov/hmcts/reform/locationrefdata/camel/processor/CourtVenueProcessor.java
  src/main/resources/application-camel-routes-common.yaml
  src/main/resources/application-lrd-router.yaml
  src/test/java/uk/gov/hmcts/reform/locationrefdata/camel/mapper/CourtVenueMapperTest.java
  src/test/java/uk/gov/hmcts/reform/locationrefdata/camel/processor/CourtVenueProcessorTest.java
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-158

#160 Add auto-update config for PR branches
  .github/workflows/autoupdate.yml
Labels: DO NOT MERGE, ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-160

#163 RDCC-2985_2: functional test build fix
  src/functionalTest/java/uk/gov/hmcts/reform/locationrefdata/cameltest/LrdCourtVenueTest.java
  src/functionalTest/resources/db/testmigration/V1_12__building_location_test_insert.sql
  src/functionalTest/resources/testData/insert-building-location.sql
  src/functionalTest/resources/testData/truncate-lrd-court-venue.sql
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-163

#165 fixed cvv
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-165

#167 RDCC-3085: Adding and Improving Mutation Tests
  Jenkinsfile_nightly
  build.gradle
  src/main/java/uk/gov/hmcts/reform/locationrefdata/camel/processor/ServiceToCcdCaseTypeProcessor.java
  src/test/java/uk/gov/hmcts/reform/locationrefdata/camel/binder/BuildingLocationTest.java
  src/test/java/uk/gov/hmcts/reform/locationrefdata/camel/binder/CourtVenueTest.java
  src/test/java/uk/gov/hmcts/reform/locationrefdata/camel/binder/ServiceToCcdCaseTypeTest.java
  src/test/java/uk/gov/hmcts/reform/locationrefdata/camel/listener/JobResultListenerTest.java
  src/test/java/uk/gov/hmcts/reform/locationrefdata/camel/processor/CourtVenueProcessorTest.java
  src/test/java/uk/gov/hmcts/reform/locationrefdata/camel/processor/ServiceToCcdCaseTypeProcessorTest.java
  src/test/java/uk/gov/hmcts/reform/locationrefdata/camel/task/LrdRouteTaskTest.java
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-167

#168 Nightly failure investigation - removed mutation step
  Jenkinsfile_nightly
  src/functionalTest/java/uk/gov/hmcts/reform/locationrefdata/cameltest/LrdApplicationExceptionAndAuditTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/locationrefdata/cameltest/LrdApplicationTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/locationrefdata/cameltest/LrdBuildingLocationFileStatusCheck.java
  src/functionalTest/java/uk/gov/hmcts/reform/locationrefdata/cameltest/LrdBuildingLocationsLoadTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/locationrefdata/cameltest/LrdCourtVenueTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/locationrefdata/cameltest/LrdFileStatusCheckTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/locationrefdata/cameltest/testsupport/LrdBlobSupport.java
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-168

#169 enabled mutation tests in the nightly job
  Jenkinsfile_nightly
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-169

#170 RDCC-3159: Changed the nightly build schedule to 14:00 BST
  Jenkinsfile_nightly
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-170

#171 RDCC-3159: Changed the nightly build schedule to 15:00 BST
  Jenkinsfile_nightly
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-171

#172 RDCC-3159: Changed the nightly build schedule to 15:30
  Jenkinsfile_nightly
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-172

#173 RDCC-3159: Changed the nightly build schedule to 18:15 UTC
  Jenkinsfile_nightly
  src/functionalTest/java/uk/gov/hmcts/reform/locationrefdata/cameltest/LrdApplicationTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/locationrefdata/cameltest/LrdBuildingLocationFileStatusCheck.java
  src/functionalTest/java/uk/gov/hmcts/reform/locationrefdata/cameltest/LrdFileStatusCheckTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/locationrefdata/cameltest/testsupport/LrdBlobSupport.java
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-173

#174 RDCC-3159: Changed the nightly build schedule to 01:21 UTC.
  Jenkinsfile_nightly
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-174

#166 RDCC-3045 - LRD: Open Issues/Features in LRD data load
  build.gradle
  src/functionalTest/java/uk/gov/hmcts/reform/locationrefdata/cameltest/LrdApplicationExceptionAndAuditTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/locationrefdata/cameltest/LrdApplicationTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/locationrefdata/cameltest/LrdBuildingLocationFileStatusCheck.java
  src/functionalTest/java/uk/gov/hmcts/reform/locationrefdata/cameltest/LrdBuildingLocationsLoadTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/locationrefdata/cameltest/LrdCourtVenueTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/locationrefdata/cameltest/LrdFileStatusCheckTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/locationrefdata/cameltest/testsupport/LrdIntegrationBaseTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/locationrefdata/config/LrdCamelConfig.java
  src/functionalTest/resources/application-integration.yml
  src/functionalTest/resources/sourceFiles/buildingLocations/building_location_test_failure_headers_jumbled_order.csv
  src/functionalTest/resources/sourceFiles/buildingLocations/building_location_test_failure_missing_header.csv
  src/functionalTest/resources/sourceFiles/buildingLocations/building_location_test_partial_success_non_existent_cluster_id.csv
  src/functionalTest/resources/sourceFiles/buildingLocations/building_location_test_partial_success_non_existent_region_id.csv
  src/functionalTest/resources/sourceFiles/buildingLocations/building_location_test_success_case_insensitive_headers.csv
  src/functionalTest/resources/sourceFiles/buildingLocations/court-venue-failure-columns-in-jumbled-order.csv
  src/functionalTest/resources/sourceFiles/court-venue-test-partial-success-non-existent-cluster.csv
  src/functionalTest/resources/sourceFiles/court-venue-test-partial-success-non-existent-court-type-id.csv
  src/functionalTest/resources/sourceFiles/court-venue-test-partial-success-non-existent-epimms-id.csv
  src/functionalTest/resources/sourceFiles/court-venue-test-partial-success-non-existent-region.csv
  src/main/java/uk/gov/hmcts/reform/locationrefdata/camel/binder/BuildingLocation.java
  src/main/java/uk/gov/hmcts/reform/locationrefdata/camel/binder/CourtVenue.java
  src/main/java/uk/gov/hmcts/reform/locationrefdata/camel/constants/LrdDataLoadConstants.java
  src/main/java/uk/gov/hmcts/reform/locationrefdata/camel/mapper/BuildingLocationMapper.java
  src/main/java/uk/gov/hmcts/reform/locationrefdata/camel/mapper/CourtVenueMapper.java
  src/main/java/uk/gov/hmcts/reform/locationrefdata/camel/processor/BuildingLocationProcessor.java
  src/main/java/uk/gov/hmcts/reform/locationrefdata/camel/processor/CourtVenueProcessor.java
  src/main/java/uk/gov/hmcts/reform/locationrefdata/camel/processor/IClusterRegionProcessor.java
  src/main/java/uk/gov/hmcts/reform/locationrefdata/camel/task/BaseTasklet.java
  src/main/java/uk/gov/hmcts/reform/locationrefdata/camel/task/LrdBuildingLocationRouteTask.java
  src/main/java/uk/gov/hmcts/reform/locationrefdata/camel/task/LrdCourtVenueRouteTask.java
  src/main/java/uk/gov/hmcts/reform/locationrefdata/camel/task/LrdOrgServiceMappingRouteTask.java
  src/main/java/uk/gov/hmcts/reform/locationrefdata/camel/util/LrdExecutor.java
  src/main/java/uk/gov/hmcts/reform/locationrefdata/camel/util/LrdLoadUtils.java
  src/main/java/uk/gov/hmcts/reform/locationrefdata/configuration/BatchConfig.java
  src/main/resources/application-camel-routes-common.yaml
  src/main/resources/application-lrd-building-location-router.yaml
  src/main/resources/application-lrd-court-venue-router.yaml
  src/main/resources/application-lrd-router.yaml
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/locationrefdata/camel/binder/BuildingLocationTest.java
  src/test/java/uk/gov/hmcts/reform/locationrefdata/camel/binder/CourtVenueTest.java
  src/test/java/uk/gov/hmcts/reform/locationrefdata/camel/mapper/BuildingLocationMapperTest.java
  src/test/java/uk/gov/hmcts/reform/locationrefdata/camel/mapper/CourtVenueMapperTest.java
  src/test/java/uk/gov/hmcts/reform/locationrefdata/camel/processor/BuildingLocationProcessorTest.java
  src/test/java/uk/gov/hmcts/reform/locationrefdata/camel/processor/CourtVenueProcessorTest.java
  src/test/java/uk/gov/hmcts/reform/locationrefdata/camel/task/LrdBuildingLocationRouteTaskTest.java
  src/test/java/uk/gov/hmcts/reform/locationrefdata/camel/task/LrdCourtVenueRouteTaskTest.java
  src/test/java/uk/gov/hmcts/reform/locationrefdata/camel/task/LrdOrgServiceMappingRouteTaskTest.java
  src/test/java/uk/gov/hmcts/reform/locationrefdata/camel/util/LrdExecutorTest.java
  src/test/java/uk/gov/hmcts/reform/locationrefdata/camel/util/LrdLoadUtilsTest.java
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-166
