Repository hmcts/rd-location-ref-data-load, pull requests merged in 2022-01, with the labels that each got.

#211 Feat:Changes made to fix bot pr issues
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-211

#226 fix: RDCC-3903 Revert the tomcat version to previous version
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-226

#212 fix: RDCC-3840 Enabled fortify scan
  Jenkinsfile_nightly
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-212
