Repository hmcts/rd-location-ref-data-load, pull requests merged in 2022-12, with the labels that each got.

#326 Replace after with afterSuccess for depreciated : RDCC-5931
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  Jenkinsfile_parameterized
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-326

#327 CVE-2021-37533 Issue Suppression : RDCC - 6007
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-327

#328 RDCC-6061: Adding Suppression for `CVE-2022-41881`
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-328

#329 RDCC-6073: Fix for `CVE-2022-41915`
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-329
