Repository hmcts/rd-location-ref-data-load, pull requests merged in 2022-08, with the labels that each got.

#293 RDCC-5261: Upgrading postgresql to version 42.4.1
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-293

#295 Add backstage configuration file
  catalog-info.yaml
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-295

#294 Refactor code to remove the hard coding
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-294
