Repository hmcts/rd-location-ref-data-load, pull requests merged in 2022-05, with the labels that each got.

#266 RDCC-4648: Increasing `CVE-2020-23171` Suppression Date
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-266

#267 fix: RDCC-4670 Fixed CVE-2022-24823 by upgrading netty
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-267

#268 RDCC-4690: Suppressing CVE-2016-1000027
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-268

#269 RDCC-4699: CVE fix for tomcat embed
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-269

#270 fix: Bumped spring dependencies version to 5.3.20
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-270

#271 Ref data - LRD load Add multi arch image configuration
  Dockerfile
  acb.tpl.yaml
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-271
