Repository hmcts/rd-location-ref-data-load, pull requests merged in 2022-10, with the labels that each got.

#316 RDCC-5534: Upgrading `snakeyaml`
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-316

#317 CVE Issue Fix- Jackson Version change 2.14.0-rc1
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-317

#320 views creation
  src/main/resources/db/migration/V1_23__create_views.sql
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-320
