Repository hmcts/rd-location-ref-data-load, pull requests merged in 2022-07, with the labels that each got.

#287 RDCC-5016: Adding Suppression for CVE-2022-33915
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-287

#288 RDCC-5064: upgraded bitnami chart version
  charts/rd-location-ref-data-load/Chart.yaml
  charts/rd-location-ref-data-load/values.preview.template.yaml
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-288

#289 RDCC-5138: Adding Suppression for `CVE-2022-31569`
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-289

#291 RDCC-5162 Delete dependabot yaml file
  .github/dependabot.yml
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-291
