Repository hmcts/rd-location-ref-data-load, pull requests merged in 2022-09, with the labels that each got.

#296 RDCC-5392: adding suppression for CVE-2022-25857
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-296

#298 fix: RDCC-5447 Suppress CVEs
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-298

#300 RDCC-5496: excluding `jettison` to fix `CVE-2022-40149` & `CVE-2022-40150`
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-300

#299 Update the Court Type to Service Association mapping for Adoption Ser…
  src/functionalTest/resources/db/testmigration/V1_21__update_Court_type_service_assoc.sql
  src/main/resources/db/migration/V1_21__update_Court_type_service_assoc.sql
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-299
