Repository hmcts/rd-location-ref-data-load, pull requests merged in 2022-03, with the labels that each got.

#246 RDCC-4140: Alter LRD tables to add new columns in Court Venue table for HMC requirements
  src/functionalTest/resources/db/testmigration/V1_15__alter_tables_add_columns.sql
  src/main/resources/db/migration/V1_15__alter_tables_add_columns.sql
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-246

#248 fix: Ignored the fortify build failure
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-248

#249 RDCC-4163: collating Dependabot PRs
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-249

#255 LRD : fix CVE-2020-36518
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-255

#256 RDCC-4331 updated for CVE 2020-36518
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-256

#254 Camel ingestion for Court Venue and Building Location
  src/functionalTest/java/uk/gov/hmcts/reform/locationrefdata/LrdDataTestConstants.java
  src/functionalTest/java/uk/gov/hmcts/reform/locationrefdata/cameltest/LrdBuildingLocationsLoadTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/locationrefdata/cameltest/LrdCourtVenueTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/locationrefdata/cameltest/testsupport/LrdIntegrationBaseTest.java
  src/functionalTest/resources/application-integration.yml
  src/functionalTest/resources/sourceFiles/buildingLocations/building_location_failure_test_no_valid_building_location.csv
  src/functionalTest/resources/sourceFiles/buildingLocations/building_location_partial_success_test_invalid_epims_id.csv
  src/functionalTest/resources/sourceFiles/buildingLocations/building_location_partial_success_test_no_epims_id.csv
  src/functionalTest/resources/sourceFiles/buildingLocations/building_location_partial_success_test_no_postcode.csv
  src/functionalTest/resources/sourceFiles/buildingLocations/building_location_success_test_no_region_cluster.csv
  src/functionalTest/resources/sourceFiles/buildingLocations/building_location_success_test_with_quotes.csv
  src/functionalTest/resources/sourceFiles/buildingLocations/building_location_test.csv
  src/functionalTest/resources/sourceFiles/buildingLocations/building_location_test_2.csv
  src/functionalTest/resources/sourceFiles/buildingLocations/building_location_test_failure_headers_jumbled_order.csv
  src/functionalTest/resources/sourceFiles/buildingLocations/building_location_test_failure_missing_header.csv
  src/functionalTest/resources/sourceFiles/buildingLocations/building_location_test_partial_success_non_existent_cluster_id.csv
  src/functionalTest/resources/sourceFiles/buildingLocations/building_location_test_partial_success_non_existent_region_id.csv
  src/functionalTest/resources/sourceFiles/buildingLocations/building_location_test_success_case_insensitive_headers.csv
  src/functionalTest/resources/sourceFiles/courtVenues/court-venue-failure-columns-in-jumbled-order.csv
  src/functionalTest/resources/sourceFiles/courtVenues/court-venue-failure.csv
  src/functionalTest/resources/sourceFiles/courtVenues/court-venue-partial-success.csv
  src/functionalTest/resources/sourceFiles/courtVenues/court-venue-test-partial-success-non-existent-cluster.csv
  src/functionalTest/resources/sourceFiles/courtVenues/court-venue-test-partial-success-non-existent-court-type-id.csv
  src/functionalTest/resources/sourceFiles/courtVenues/court-venue-test-partial-success-non-existent-epimms-id.csv
  src/functionalTest/resources/sourceFiles/courtVenues/court-venue-test-partial-success-non-existent-region.csv
  src/functionalTest/resources/sourceFiles/courtVenues/court-venue-test.csv
  src/main/java/uk/gov/hmcts/reform/locationrefdata/camel/binder/BuildingLocation.java
  src/main/java/uk/gov/hmcts/reform/locationrefdata/camel/binder/CourtVenue.java
  src/main/java/uk/gov/hmcts/reform/locationrefdata/camel/constants/LrdDataLoadConstants.java
  src/main/java/uk/gov/hmcts/reform/locationrefdata/camel/mapper/BuildingLocationMapper.java
  src/main/java/uk/gov/hmcts/reform/locationrefdata/camel/mapper/CourtVenueMapper.java
  src/main/java/uk/gov/hmcts/reform/locationrefdata/camel/util/LrdLoadUtils.java
  src/main/resources/application-lrd-building-location-router.yaml
  src/main/resources/application-lrd-court-venue-router.yaml
  src/test/java/uk/gov/hmcts/reform/locationrefdata/camel/binder/BuildingLocationTest.java
  src/test/java/uk/gov/hmcts/reform/locationrefdata/camel/binder/CourtVenueTest.java
  src/test/java/uk/gov/hmcts/reform/locationrefdata/camel/mapper/BuildingLocationMapperTest.java
  src/test/java/uk/gov/hmcts/reform/locationrefdata/camel/mapper/CourtVenueMapperTest.java
  src/test/java/uk/gov/hmcts/reform/locationrefdata/camel/processor/BuildingLocationProcessorTest.java
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-254

#258 CVE fix
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-258
