Repository hmcts/rd-location-ref-data-load, pull requests merged in 2022-04, with the labels that each got.

#260 RDCC-4402: CVE Fix
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-260

#261 updated for CVe Fixes
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-261

#259 JDK17 upgrade changes
  Dockerfile
  build.gradle
  docker-compose.yml
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-259
