Repository hmcts/rd-location-ref-data-load, pull requests merged in 2023-11, with the labels that each got.

#387 DTSRD-1466.Updating schema parameter with hibernate
  src/main/resources/application.yaml
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-387

#388 Update suppressions.xml to fix CVE-2023-4759
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-388

#389 Update acb.tpl.yaml
  acb.tpl.yaml
  charts/rd-location-ref-data-load/Chart.yaml
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-389

#390 CVE-2023-36052 suppression
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-390

#392 Addresses CVE-2023-35887
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-392
