Repository hmcts/rd-location-ref-data-load, pull requests merged in 2023-06, with the labels that each got.

#371 Suppress CVE-2023-20883
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-371

#370 Update README.md
  README.md
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-370

#373 Update suppressions.xml
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-373
