Repository hmcts/rd-location-ref-data-load, pull requests merged in 2023-05, with the labels that each got.

#352 Upgraded to gradle wrapper 7.4.2
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-352

#362 addresses CVE-2023-20873, CVE-2023-20862
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-362

#363 Addresses CVE-2021-22044
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-363

#365 DTSPO-13810 reschedule jenkins nightly builds
  Jenkinsfile_nightly
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-365

#368 Upgrade chart-job to v 1.0.0
  charts/rd-location-ref-data-load/Chart.yaml
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-368

#366 [RDCC 6746]-upgrade deprecated methods to java 17
  src/functionalTest/java/uk/gov/hmcts/reform/locationrefdata/cameltest/testsupport/LrdIntegrationBaseTest.java
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-366
