Repository hmcts/rd-location-ref-data-load, pull requests merged in 2023-03, with the labels that each got.

#342 changing slack notification channel for pr build updates
  Jenkinsfile_CNP
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-342

#345 RDCC-6464: Adding Suppression for CVE-2023-24998
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-345

#346 [RDCC-6437] Fix of header validation for Court-venue and building location files
  src/main/resources/application-lrd-building-location-router.yaml
  src/main/resources/application-lrd-court-venue-router.yaml
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-346

#343 Feat:Address CVEs in all Reference Data repositories - Location Reference Data
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-343

#348 [RDCC-6561]- Location : Add header validation to check UTF-8 file format
  build.gradle
  src/functionalTest/java/uk/gov/hmcts/reform/locationrefdata/cameltest/LrdBuildingLocationsLoadTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/locationrefdata/cameltest/LrdCourtVenueTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/locationrefdata/cameltest/testsupport/LrdIntegrationBaseTest.java
  src/functionalTest/resources/sourceFiles/buildingLocations/building_location_utf8_header.csv
  src/functionalTest/resources/sourceFiles/courtVenues/court-venue-utf8-header-success.csv
  src/main/resources/application-lrd-building-location-router.yaml
  src/main/resources/application-lrd-court-venue-router.yaml
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-348

#347 Sonar issues been addressed
  src/main/java/uk/gov/hmcts/reform/locationrefdata/camel/processor/ServiceToCcdCaseTypeProcessor.java
  src/main/java/uk/gov/hmcts/reform/locationrefdata/camel/util/LrdLoadUtils.java
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-347

#350 RDCC-6611: suppress CVE-2022-1471
  charts/rd-location-ref-data-load/Chart.yaml
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-350

#349 RDCC-6594: Upgrade Libs
  Dockerfile
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, no-changes, rel:rd-location-ref-data-load-pr-349

#351 Nightly build failure
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-351

#356 Nightly build failure
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-356
