Repository hmcts/rd-location-ref-data-load, pull requests merged in 2023-12, with the labels that each got.

#393 Addresses CVE-2023-33202
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-393

#394 Addresses CVE-2023-34055, CVE-2023-46589
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-394

#395 Addresses CVE-2023-6378
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-395

#396 Update dependencycheck to use default version
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-396

#397 suppress CVE-2023-48795
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-397
