Repository hmcts/rd-location-ref-data-load, pull requests merged in 2023-07, with the labels that each got.

#375 Update build.gradle
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-375

#377 Suppress CVE-2023-34442 - working on fix
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-377

#379 CVE: Address CVE-2023-34034
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-379
