Repository hmcts/rd-location-ref-data-load, pull requests merged in 2023-10, with the labels that each got.

#383 DTSRD-1456
  build.gradle
  charts/rd-location-ref-data-load/Chart.yaml
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-383

#384 Addresses CVE-2023-42794, CVE-2023-42795 and CVE-2023-45648
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-384

#385 suppress CVE-2023-5072
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-385

#386 DTSRD-1456.suppressing as no known netty handler version available without vulnerability
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-386
