Repository hmcts/rd-location-ref-data-load, pull requests merged in 2024-11, with the labels that each got.

#528 DTSRD-3674 Dataload Mutation Tests BootClassPathSupported False Error…
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-528

#530 DTSRD-3685 CVE-2024-38820 Suppression
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-530

#533 DTSRD-3710 Revert "Update dependency org.pitest:pitest to v1.17.1"
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-533

#507 DTSRD-1992- Add a check for zero byte characters durng file upload
  src/functionalTest/java/uk/gov/hmcts/reform/locationrefdata/cameltest/LrdBuildingLocationsLoadTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/locationrefdata/cameltest/LrdCourtVenueTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/locationrefdata/config/LrdCamelConfig.java
  src/functionalTest/resources/application-integration.yml
  src/functionalTest/resources/sourceFiles/buildingLocations/building_location_0_byte_character.csv
  src/functionalTest/resources/sourceFiles/courtVenues/court-venue-0-byte-character.csv
  src/main/java/uk/gov/hmcts/reform/locationrefdata/camel/binder/BuildingLocation.java
  src/main/java/uk/gov/hmcts/reform/locationrefdata/camel/binder/CourtVenue.java
  src/main/java/uk/gov/hmcts/reform/locationrefdata/camel/processor/BuildingLocationProcessor.java
  src/main/java/uk/gov/hmcts/reform/locationrefdata/camel/processor/CourtVenueProcessor.java
  src/main/java/uk/gov/hmcts/reform/locationrefdata/camel/processor/IClusterRegionProcessor.java
  src/main/java/uk/gov/hmcts/reform/locationrefdata/configuration/DataQualityCheckConfiguration.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/locationrefdata/camel/processor/BuildingLocationProcessorTest.java
  src/test/java/uk/gov/hmcts/reform/locationrefdata/camel/processor/CourtVenueProcessorTest.java
Labels: ns:rd, prd:rd, aat/no-changes, prod/no-changes, rel:rd-location-ref-data-load-pr-507

#517 DTSRD-3404: Upgrade to spring boot 3
  build.gradle
  config/owasp/suppressions.xml
  database/Dockerfile
  src/functionalTest/java/uk/gov/hmcts/reform/locationrefdata/cameltest/LrdApplicationExceptionAndAuditTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/locationrefdata/cameltest/LrdApplicationTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/locationrefdata/cameltest/LrdBuildingLocationFileStatusCheck.java
  src/functionalTest/java/uk/gov/hmcts/reform/locationrefdata/cameltest/LrdBuildingLocationsLoadTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/locationrefdata/cameltest/LrdCourtVenueTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/locationrefdata/cameltest/LrdFileStatusCheckTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/locationrefdata/cameltest/testsupport/LrdBlobSupport.java
  src/functionalTest/java/uk/gov/hmcts/reform/locationrefdata/config/LrdCamelConfig.java
  src/functionalTest/resources/application-integration.yml
  src/main/java/uk/gov/hmcts/reform/locationrefdata/camel/binder/BuildingLocation.java
  src/main/java/uk/gov/hmcts/reform/locationrefdata/camel/binder/CourtVenue.java
  src/main/java/uk/gov/hmcts/reform/locationrefdata/camel/binder/ServiceToCcdCaseType.java
  src/main/java/uk/gov/hmcts/reform/locationrefdata/camel/processor/ServiceToCcdCaseTypeProcessor.java
  src/main/java/uk/gov/hmcts/reform/locationrefdata/camel/util/LrdExecutor.java
  src/main/java/uk/gov/hmcts/reform/locationrefdata/camel/util/LrdLoadUtils.java
  src/main/java/uk/gov/hmcts/reform/locationrefdata/configuration/BatchConfig.java
  src/main/resources/application-camel-routes-common.yaml
  src/main/resources/application-lrd-building-location-router.yaml
  src/main/resources/application-lrd-court-venue-router.yaml
  src/main/resources/application-lrd-router.yaml
  src/test/java/uk/gov/hmcts/reform/locationrefdata/camel/processor/BuildingLocationProcessorTest.java
  src/test/java/uk/gov/hmcts/reform/locationrefdata/camel/processor/CourtVenueProcessorTest.java
  src/test/java/uk/gov/hmcts/reform/locationrefdata/camel/processor/ServiceToCcdCaseTypeProcessorTest.java
Labels: ns:rd, prd:rd, aat/no-changes, prod/no-changes, rel:rd-location-ref-data-load-pr-517

#538 Addresses master build failure
  infrastructure/terraform.tf
Labels: ns:rd, prd:rd, aat/no-changes, prod/no-changes, rel:rd-location-ref-data-load-pr-538

#541 DTSRD-3404: Fix aat deployment issue
  build.gradle
Labels: ns:rd, prd:rd, enable_keep_helm, rel:rd-location-ref-data-load-pr-541

#553 Restore azurerm 3.106
  infrastructure/terraform.tf
Labels: ns:rd, prd:rd, aat/no-changes, prod/no-changes, rel:rd-location-ref-data-load-pr-553

#555 spring-boot 3.3.5
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-555

#564 Update Chart to 0.0.34
  charts/rd-location-ref-data-load/Chart.yaml
Labels: ns:rd, prd:rd, aat/no-changes, prod/no-changes, rel:rd-location-ref-data-load-pr-564
