Repository hmcts/rd-location-ref-data-load, pull requests merged in 2024-04, with the labels that each got.

#402 DTSRD-2505: Add new column (Short_Court_Name) to the court_venue table
  src/functionalTest/resources/application-integration.yml
  src/functionalTest/resources/db/testmigration/V1_22__alter_tables_add_columns.sql
  src/functionalTest/resources/sourceFiles/courtVenues/court-venue-failure-columns-in-jumbled-order.csv
  src/functionalTest/resources/sourceFiles/courtVenues/court-venue-failure.csv
  src/functionalTest/resources/sourceFiles/courtVenues/court-venue-partial-success.csv
  src/functionalTest/resources/sourceFiles/courtVenues/court-venue-test-partial-success-non-existent-cluster.csv
  src/functionalTest/resources/sourceFiles/courtVenues/court-venue-test-partial-success-non-existent-court-type-id.csv
  src/functionalTest/resources/sourceFiles/courtVenues/court-venue-test-partial-success-non-existent-epimms-id.csv
  src/functionalTest/resources/sourceFiles/courtVenues/court-venue-test-partial-success-non-existent-region.csv
  src/functionalTest/resources/sourceFiles/courtVenues/court-venue-test.csv
  src/functionalTest/resources/sourceFiles/courtVenues/court-venue-utf8-header-success.csv
  src/main/java/uk/gov/hmcts/reform/locationrefdata/camel/binder/CourtVenue.java
  src/main/java/uk/gov/hmcts/reform/locationrefdata/camel/mapper/CourtVenueMapper.java
  src/main/resources/application-lrd-court-venue-router.yaml
  src/main/resources/application.yaml
  src/main/resources/db/migration/V1_22__alter_tables_add_columns.sql
  src/test/java/uk/gov/hmcts/reform/locationrefdata/camel/binder/CourtVenueTest.java
  src/test/java/uk/gov/hmcts/reform/locationrefdata/camel/mapper/CourtVenueMapperTest.java
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-402

#403 Dtsrd 2540
  src/functionalTest/resources/db/testmigration/V1_22__alter_tables_add_columns.sql
  src/functionalTest/resources/db/testmigration/V1_22__lrd_mi_reporting.sql
  src/functionalTest/resources/db/testmigration/V1_23__create_views.sql
  src/functionalTest/resources/db/testmigration/V1_24__drop_indexes.sql
  src/functionalTest/resources/db/testmigration/V1_25__alter_tables_add_columns.sql
  src/main/resources/application.yaml
  src/main/resources/db/migration/V1_22__alter_tables_add_columns.sql
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-403

#405 Update pitest
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-location-ref-data-load-pr-405
